### ISSUE TITLE
getVideoById returns undefined 

### ISSUE THREAD

**Issue by erwinkramer** [JohnnyTheTank/angular-youtube-api-factory#11]
If i call `youtubeFactory.getVideoById` and check my network, i see a valid request to the YouTube API and i get back a valid JSONresponse. It comes in the `.then(function (_data)` block and not in the `catch`, as expected. However, i call a `console.log(_data.kind);` and it returns `undefined`. What's the issue here?

**Comment by JohnnyTheTank** [comment]
I guess you should call `console.log(_data.data.kind);`

**Comment by erwinkramer** [comment]
@JohnnyTheTank thanks! That's it. What's the logic here anyway, why is it in another data object?

Maybe nice to provide such an example in your demo or the readme for completeness.

**Comment by JohnnyTheTank** [comment]
that's how youtube provides the data. it's not about me ;)

but that's a good idea to provide demo. i will create a working plnkr
